[package]
name = "rs-pcb2gcode-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.9.0", package = "gtk4", features = ["v4_12"] }

[build-dependencies]
glib-build-tools = "0.20.0"
