[package]
name = "rs-pcb2gcode-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "5.0.1"
gtk = { version = "0.9.0", package = "gtk4", features = ["v4_12"] }
rusqlite = { version = "0.32.1", features = ["bundled"] }

[build-dependencies]
glib-build-tools = "0.20.0"
